import js from '@eslint/js';
import prettierConfig from 'eslint-config-prettier/flat';
import prettierPlugin from 'eslint-plugin-prettier';

const nodeGlobals = {
	AbortController: 'readonly',
	AbortSignal: 'readonly',
	Blob: 'readonly',
	Buffer: 'readonly',
	URL: 'readonly',
	URLSearchParams: 'readonly',
	clearImmediate: 'readonly',
	clearInterval: 'readonly',
	clearTimeout: 'readonly',
	console: 'readonly',
	fetch: 'readonly',
	global: 'readonly',
	process: 'readonly',
	queueMicrotask: 'readonly',
	setImmediate: 'readonly',
	setInterval: 'readonly',
	setTimeout: 'readonly',
};

export default [
	{
		ignores: ['coverage/**', 'node_modules/**'],
	},
	js.configs.recommended,
	prettierConfig,
	{
		files: ['**/*.js', '**/*.mjs'],
		languageOptions: {
			ecmaVersion: 'latest',
			sourceType: 'module',
			globals: nodeGlobals,
		},
		plugins: {
			prettier: prettierPlugin,
		},
		rules: {
			'array-callback-return': 'error',
			'block-scoped-var': 'error',
			curly: ['error', 'all'],
			eqeqeq: ['error', 'always'],
			'func-style': ['error', 'declaration', { allowArrowFunctions: true }],
			'logical-assignment-operators': ['error', 'always'],
			'no-alert': 'error',
			'no-await-in-loop': 'error',
			'no-bitwise': 'error',
			'no-caller': 'error',
			'no-console': 'off',
			'no-else-return': ['error', { allowElseIf: false }],
			'no-empty-function': 'error',
			'no-eval': 'error',
			'no-extend-native': 'error',
			'no-extra-bind': 'error',
			'no-implicit-coercion': 'error',
			'no-implied-eval': 'error',
			'no-invalid-this': 'error',
			'no-iterator': 'error',
			'no-labels': 'error',
			'no-lone-blocks': 'error',
			'no-magic-numbers': [
				'error',
				{
					ignore: [-1, 0, 1, 2, 100],
					ignoreArrayIndexes: true,
					ignoreDefaultValues: true,
				},
			],
			'no-multi-assign': 'error',
			'no-new': 'error',
			'no-new-func': 'error',
			'no-new-wrappers': 'error',
			'no-object-constructor': 'error',
			'no-param-reassign': 'error',
			'no-promise-executor-return': 'error',
			'no-proto': 'error',
			'no-return-await': 'error',
			'no-script-url': 'error',
			'no-self-compare': 'error',
			'no-sequences': 'error',
			'no-template-curly-in-string': 'error',
			'no-throw-literal': 'error',
			'no-undef-init': 'error',
			'no-unmodified-loop-condition': 'error',
			'no-unneeded-ternary': 'error',
			'no-unreachable-loop': 'error',
			'no-unused-expressions': [
				'error',
				{
					allowShortCircuit: false,
					allowTernary: false,
					allowTaggedTemplates: false,
				},
			],
			'no-unused-vars': [
				'error',
				{
					args: 'after-used',
					argsIgnorePattern: '^_',
					caughtErrors: 'all',
					caughtErrorsIgnorePattern: '^_',
					varsIgnorePattern: '^_',
				},
			],
			'no-use-before-define': [
				'error',
				{
					functions: false,
					classes: true,
					variables: true,
				},
			],
			'no-useless-assignment': 'error',
			'no-useless-call': 'error',
			'no-useless-computed-key': 'error',
			'no-useless-concat': 'error',
			'no-useless-rename': 'error',
			'no-var': 'error',
			'object-shorthand': ['error', 'always'],
			'one-var': ['error', 'never'],
			'operator-assignment': ['error', 'always'],
			'prefer-arrow-callback': ['error', { allowNamedFunctions: false }],
			'prefer-const': ['error', { destructuring: 'all' }],
			'prefer-destructuring': [
				'error',
				{
					array: false,
					object: true,
				},
				{
					enforceForRenamedProperties: false,
				},
			],
			'prefer-exponentiation-operator': 'error',
			'prefer-numeric-literals': 'error',
			'prefer-object-has-own': 'error',
			'prefer-object-spread': 'error',
			'prefer-promise-reject-errors': 'error',
			'prefer-regex-literals': ['error', { disallowRedundantWrapping: true }],
			'prefer-rest-params': 'error',
			'prefer-spread': 'error',
			'prettier/prettier': [
				'error',
				{
					singleQuote: true,
					useTabs: true,
					printWidth: 100,
					trailingComma: 'all',
				},
			],
			radix: 'error',
			'require-atomic-updates': 'error',
			strict: ['error', 'never'],
			yoda: 'error',
		},
	},
	{
		files: ['**/*.test.js', '**/*.spec.js', 'src/specs/**/*.js'],
		rules: {
			'func-style': 'off',
			'no-empty-function': 'off',
			'no-magic-numbers': 'off',
			'prefer-destructuring': 'off',
		},
	},
	{
		files: ['src/init.js'],
		rules: {
			'no-await-in-loop': 'off',
		},
	},
];
